### ISSUE TITLE
build_monitors_from_dict line 28

### ISSUE THREAD

**Issue by muttleyxd** [GabMus/HydraPaper#3] opened 2018-01-23 23:20 UTC
Unfortunately I do not know what's wrong here, GNOME 3.26 on Arch Linux, 2 monitors used on Intel IGPU (7700K)

```
Traceback (most recent call last):
  File "/usr/bin/hydrapaper", line 51, in <module>
    __main__.main()
  File "/usr/lib/python3.6/site-packages/hydrapaper/__main__.py", line 368, in main
    application = Application()
  File "/usr/lib/python3.6/site-packages/hydrapaper/__main__.py", line 78, in __init__
    self.monitors = MonitorParser.build_monitors_from_dict()
  File "/usr/lib/python3.6/site-packages/hydrapaper/monitor_parser.py", line 28, in build_monitors_from_dict
    lm_list = doc['monitors']['configuration'][-1]['logicalmonitor']
KeyError: -1

```

**Comment by GabMus** [comment] 2018-01-23 23:53
please send output of `cat .config/monitors.xml`

**Comment by GabMus** [comment] 2018-01-24 01:14
Probably a duplicate of #1 

As I suggested in the other issue, try this new flatpak: [hydrapaper-11faa4d.zip](https://github.com/GabMus/HydraPaper/files/1658156/hydrapaper-11faa4d.zip)

**Comment by GabMus** [comment] 2018-01-24 11:21
should be fixed, closing

**Closed as completed by GabMus** 2018-01-24 11:21 UTC
